server:
  error:
    include-stacktrace: always

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/employeeo-db?createDatabaseIfNotExist=true
    username: root
    password: password